Alfresco/acs-community-packaging

docker-alfresco/test/docker-compose.yml
docker-compose/docker-compose.yml
helm/alfresco-content-services-community/requirements.yaml
helm/alfresco-content-services-community/values.yaml
pom.xml

Update the images to use **Postgres 10.1** and postgresql **driver 42.2.1**

WIP: REPO:3300: Deployment: 6.0 Base Images Stack Alignment

---

pom.xml
war/pom.xml

* Remove javax.portlet:portlet-api dependecy
* Update remote-api version

REPO-3428: EOL Library JSR-168 Portlets API

---

pom.xml

* Update alfresco-repository version to 6.46

REPO-3329: Record deployment method

---

war/src/main/resources/log4j.properties

…use them ourselves in community.

REPO-3425 tika docker transformer

---

pom.xml

REPO-3688 Renditions: Deprecation of public Java APIs

REPO-3766 Renditions: Simplified Async Rendition Service

---

pom.xml

[ MNT-19577 ] Updated alfresco-data-model version (8.18 -> 8.19)

---

distribution/pom.xml
docker-alfresco/Dockerfile
docker-alfresco/pom.xml

Official Alfresco Docker Image Missing vti-bin war file

REPO-3943: Service Pack: MNT-20042: Alfresco Docker Image Missing

---

pom.xml

alfresco-data-model 8.25
alfresco-repository 7.39
alfresco-remote-api repo-4114-1

v1 POST /nodes/{nodeId}/children api does not use Transform Service

---

pom.xml

alfresco-repository 7.43
alfresco-remote-api 7.35

Update dependencies (library upgrades)

---

CHANGELOG.md
docker-alfresco/Dockerfile
docker-alfresco/pom.xml

REPO-4026 : Update CHANGELOG.md  for Community 201901 GA
simplify Dockerfile

Merge feature/REPO-4126_community_201901 into master

---

war/src/main/webapp/WEB-INF/web.xml

* add missing cors.supportedHeaders range
* cors.exposedHeaders

REPO-4217 Add missing cors configuration

---

docker-alfresco/Dockerfile
pom.xml

- Create extension directories in Docker image
- Remove external executables from docker image now community has T-Engines

REPO-4589 Configure Mimetypes for custom renditions

---

pom.xml

REPO-4631 Update jackson-databind version to 2.9.9.3

REPO-4631 Update jackson-databind version to 2.9.9.3 

---

pom.xml
tests/tas-restapi/src/test/java/org/alfresco/rest/renditions/AvailableRenditionTests.java

Bump remote-api to 8.73
Bump repository to 8.61
Bump data-model to 8.75
Bump core to 8.12
Bump api-explorer to 6.2.1

REPO-4917 : Update upstream projects

---

pom.xml

* update *alfresco-remote-api* version from 7.122 to 7.123
* update *alfresco-repository* version from 7.164 to 7.167
* update *alfresco-data-model* version from 8.50.9 to 8.50.10
* update *alfresco-core* version from 7.30 to 7.31

MNT-19887: Pick up 6.2.N upstream projects

---

.travis.yml

This new build job will publish (update) the **quay.io/alfresco-content-repository:latest** image on each new update on the *develop* branch.

ACS-550 Update latest image from the develop branch (on Quay only)

---

README.md
tests/environment/docker-compose-minimal+transforms.yml
tests/environment/docker-compose-minimal.yml

Update references to acs-community-deployment to acs-deployment

OPSEXP-517: Update deployment references

---

pom.xml

APPS-553: Share version 7.0.0-M2 doesn't display the correct version

---

pom.xml

- PR in acs-community-packaging for Share 7.0.0-A6

APPS-595 : Changes from MNT-20195 break Travis build for alfresco-community-repo

---

pom.xml

ACS-741 : SAML - Logout is not working on Chrome

---

pom.xml

MNT-18497 : Displaying Folder With Many Linked Nodes is Slow in Share

---

pom.xml

Updated the REST API Explorer to the latest version, upgraded to Swagger UI 3: https://github.com/Alfresco/rest-api-explorer/releases

Updated the API Explorer to the latest version

---

distribution/pom.xml
pom.xml
tests/tas-integration/pom.xml
tests/tas-restapi/pom.xml

- remove unnecessary dependency declarations & dependency excludes

ACS-1146 Replace *javax* dependencies with *jakarta* libraries

---

pom.xml

acs community version change 7.0.1

bump-share-7.0.1

---

.travis.yml
distribution/src/assembly/distribution.xml
tests/pom.xml
tests/tas-distribution-zip/pom.xml
tests/tas-distribution-zip/src/test/java/org/alfresco/distribution/CheckDistributionZipContents.java
tests/tas-distribution-zip/src/test/resources/distribution-suite.xml

A simple class to check some of the expected files in distribution zip of:
- ACS
- AGS

ACS-106: No tests check that the distribution zip contains files from the main components

---

scripts/travis/copy_ags_to_release_bucket.sh
scripts/travis/copy_to_release_bucket.sh
scripts/travis/prepare_staging_deploy.sh

Also ensure the report contains information about the Repo _and_ Share.

ACS-2304 Copy license report to downloads bucket.

---

.github/workflows/ci.yml

Replace `contains` with `startsWith` for better branch detection.

ACS-3750 Improve branch detection in if conditions

---

.github/workflows/ci.yml

ACS-3750 Use set Git token instead of cached one

---

tests/tas-restapi/pom.xml

Ref. [ACS-5087](https://alfresco.atlassian.net/browse/ACS-5087)
[ACS-5087]: https://alfresco.atlassian.net/browse/ACS-5087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACS-5087 Add missing awaitility dependency
