Alfresco/acs-community-packaging

docker/pom.xml
pom.xml
war/pom.xml
zip/pom.xml

The project version is changed to 6.0.0 and that version is then propagated to [version.properties](https://github.com/Alfresco/acs-community-packaging/blob/develop/war/src/main/resources/alfresco/version.properties)

REPO-2886 Change the project version to 6.0.0

---

pom.xml
war/pom.xml
zip/src/main/resources/licenses/notice.txt

The commons-modeler has commons-digester as a dependency. It appeared
that the modeler is not used, so was removed. Commons-digester is still a
dependency for commons-validator and newer version of commons-digester
needs to be enforced.

REPO-3120 Remove commons-modeler as unused

---

docker-alfresco/test/docker-compose.yml
pom.xml

-  Adding parameter Dcifs.enabled=true on test/docker compose
-  Upgrade alfresco-repository version to 6.34

REPO-3256: EOL:Disable CIFS and FTP by default

---

docker-alfresco/Dockerfile

Use alfresco-base-tomcat:8.5.28-java-8-oracle-centos-7-f7b1278cc0eb image that has **Tomcat 8.5.28** and **Java 1.8.0_161-b12** to create a community image similar to ACS 6.0 Stack 5.

REPO-3300: Deployment: 6.0 Base Images Stack 

---

pom.xml

Quartz uses c3p0 jdbc pool for it's distributed job storage since version 2.x
This commit will exclude c3p0 lib as distributed job storage is not used.

REPO-3447 Remove c3p0

---

pom.xml

- Update version of dependencies: alfresco-messaging-repo (1.2.9) and alfresco-events (1.2.12)

APPSREPO-433 : Update messaging-repo and events libs

---

docker-alfresco/pom.xml
pom.xml

- updated googledocs dependencies

GOOGLEDOCS-429 : Generate RC2 for GoogleDocs 3.1.0 compatible with ACS Ent 6.0

---

pom.xml

GOOGLEDOCS-437 : Generate Final Build for GoogleDocs 3.1.0 compatible with ACS Ent 6.0

---

docker-alfresco/pom.xml
pom.xml
war/src/main/webapp/index.jsp

Add alfresco-api-explorer version property to pom.xml
Add alfresco-api-explorer dependency to docker-alfresco/pom.xml and unpack it using maven-dependency-plugin
Marked "Alfresco WebScripts - Home" as internal
Add url api-explorer to index.jsp

REPO-3539 : Integrate Api-Explorer

---

docker-alfresco/Dockerfile

The workflow diagrams could not be generated because sun.font package classes require system fonts to be installed.
The current docker image requires additional package (fontconfig) to be added. It's version and the versions of the dependencies were pinned.

REPO-3973 Activiti workflow compatibility

---

docker-alfresco/Dockerfile
docker-alfresco/pom.xml

- All licenses (including 3rd party) should be under /licenses directory of the docker image.

REPO-4172: Add Licenses directory to the root of docker image

---

.gitignore
distribution/src/main/resources/keystore/CreateSSLKeystores.txt
distribution/src/main/resources/keystore/generate_keystores.bat
distribution/src/main/resources/keystore/generate_keystores.sh
distribution/src/main/resources/keystore/readme.txt

Moved files from alfresco-repository, that was describing the process of creating ssl.keystore and ssl.truststore files.

REPO-4400: Remove ssl.keystore and ssl.truststore from alfresco repository.jar

---

pom.xml
tests/tas-cmis/src/test/java/org/alfresco/cmis/RepositoryInfoTests.java
tests/tas-email/src/test/java/org/alfresco/email/imap/ImapCopyMessagesTests.java

With Dependabot enabled on the following repos:
[alfresco-tas-restapi](https://github.com/Alfresco/alfresco-tas-restapi)
[alfresco-tas-cmis](https://github.com/Alfresco/alfresco-tas-cmis)
[alfresco-tas-ftp](https://github.com/Alfresco/alfresco-tas-ftp)
[alfresco-tas-email](https://github.com/Alfresco/alfresco-tas-email)
[alfresco-tas-webdav](https://github.com/Alfresco/alfresco-tas-webdav) 
Changes have been made, where required to fix broken tests.
Cherry-picked from [acs-packaging #776](https://github.com/Alfresco/acs-packaging/pull/776)

REPO-4739 update dependencies of tas framework (#776)

---

distribution/src/main/resources/licenses/notice.txt
pom.xml
war/pom.xml

- remove workaround - no longer needed

GOOGLEDOCS-461 : Remove old commons-lang lib from Repo AMP dependencies

---

docker-alfresco/Dockerfile

Since upgrading to fabric8-maven-plugin:4.x.x the docker image creation has failed on Windows. It appear that the variable USERNAME it cannot be set by the plugin and the current logged in user name is used instead. This is prevents the alfresco user being created correctly and also causes errors when trying to apply amps.
Renaming the variable fixes this issue.

REPO-5037 Fix fabric8 build error on Windows

---

pom.xml

Currently ACS 6.2.1-RC3 contains a reference to rest-api-explorer 6.3.0. This is wrong. There is a released 6.2.1 version but there have been more commits since. This PR updates develop in order to use 6.2.1.1 version (released 29/04/20) which include these additional commits.

ACS-100 Update api-explorer to 6.2.1.1

---

war/pom.xml

cors-filter jar was missing in 6.2.1 release. ACS fails to start if CORS is enabled(cors.enabled=true) in alfresco-global.properties because of the missing jars.

Added cors-filter dependency

---

tests/tas-restapi/src/test/java/org/alfresco/rest/servlet/DownloadContentServletTests.java
tests/tas-restapi/src/test/resources/test-suites/part1-suite.xml
war/src/main/java/org/alfresco/web/app/servlet/DownloadContentServlet.java
war/src/main/webapp/WEB-INF/web.xml

Remove doHEAD method from DownloadContentServlet
doGET method now redirects to V1 REST - GET /nodes/{nodeId}
Removed leftover org.alfresco.web.app.servlet.UploadContentServlet, org.alfresco.web.app.servlet.DownloadRawContentServlet and org.alfresco.web.app.servlet.GuestDownloadContentServlet from web.xml as those servlet implementation does not exist.
Refactor javadoc.
Add TAS tests to Rest-API/DownloadContentServletTests class
Restrict DownloadContentServlet to allow only nodes from the workspace://SpacesStore/

MNT-21602 : Revive DownloadContentServlet.java

---

.travis.settings.xml
scripts/travis/init.sh

- **scripts/travis/init.sh**: execute the docker logins only on branch builds
- **~/.m2/settings.xml**: remove `quay.io` & `docker.io` server definitions
(the docker logins in the init.sh script should be enough)

ACS-896 Fix community PR builds

---

tests/tas-email/src/test/java/org/alfresco/email/imap/ImapReadMessagesAcsTests.java

Part of Epic: ACS-959 Fix or suppress the content repository's intermittent test failures

ACS-960 Disable very frequent intermittent test failures

---

dev/aliases
scripts/dev/start-compose.sh

The `envUp` alias was malformed, referring to `acs-packaging` instead of `acs-community-packaging`, and unusable from the parent directory as opposed to the previous behaviour _(documented [here](https://github.com/Alfresco/acs-community-packaging/blob/master/dev/README.md?plain=1#L68-L71))_. This PR fixes the alias and restores the original behaviour.

Fix broken 'envUp' alias

---

.travis.yml
pom.xml
scripts/travis/build.sh
tests/tas-integration/pom.xml
tests/tas-restapi/pom.xml

Upgrade Travis runtime to Java 17.
This needs https://github.com/Alfresco/alfresco-enterprise-share/pull/261 to be merged and propagated to https://github.com/Alfresco/alfresco-community-share.

ACS-3347 Upgrade to Java 17

---

scripts/travis/build.sh

These `MAVEN_OPTS` to open reflective access at compile time were necessary when Share was not compatible with Java 17 yet. It's safe to assume this workaround is not needed anymore since Share has been upgraded to be compatible with Java 17.

APPS-1677 Remove unnecessary MAVEN_OPTS when building Share

---

docker-alfresco/pom.xml
docker-share/ags/pom.xml

Removing the provenance layer since it causes issues with the manifest and labels parsing and rendering on the quay.io UI.

ACS-4063 Remove provenance layer to address PROJQUAY-5013

---

.github/dependabot.yml

Removed ignores for the following dependencies:
- org.apache.tomcat.embed
- org.apache.tomcat
- io.fabric8:fabric8-maven-plugin - no longer used as was replaced by docker-maven-plugin
- org.alfresco:api-explorer - because already using 23.1.0-A1
- org.alfresco.integrations:alfresco-googledocs-repo-community - not referenced in project
- org.alfresco.integrations:alfresco-googledocs-share-community - not referenced in project

ACS-5905 Remove outdated dependabot overrides

---

.github/workflows/ci.yml

- Migrate from `Node16` to `Node20`.
- Additionally: upgrading the version to the latest for other actions from the `alfresco-build-tools`.

ACS-8670 Deal with upcoming GitHub Actions deprecations
